# rustflags には rustc を呼び出すたびに自動的に追加される引数が含まれています。
# .cargo/config.toml についての詳細は公式のドキュメントを確認してください。
# これで私達のプログラムは3つすべてのプラットフォーム上で、シンプルに cargo build のみでビルドすることができるようになります。

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]