# build-stdオプション
#   Rustのソースコードを自作OS向けに再コンパイル
#
# メモリ関係の組み込み関数(build-std-features)
#   compiler_builtinsクレートより使用できるようにする

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

# 標準のターゲットをセットする
[build]
target = "x86_64-blog_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"